"""Mod 查詢服務共用常數"""

from __future__ import annotations

from ....utils import get_logger

logger = get_logger().bind(component="ModSearchService")
MODRINTH_SEARCH_URL = "https://api.modrinth.com/v2/search"
MODRINTH_PROJECT_URL = "https://modrinth.com/mod"
MODRINTH_PROJECT_BATCH_URL = "https://api.modrinth.com/v2/projects"
MODRINTH_VERSION_URL_TEMPLATE = "https://api.modrinth.com/v2/project/{project_id}/version"
MODRINTH_VERSION_DETAIL_URL_TEMPLATE = "https://api.modrinth.com/v2/version/{version_id}"
MODRINTH_VERSION_FILES_URL = "https://api.modrinth.com/v2/version_files"
MODRINTH_VERSION_FILES_UPDATE_URL = "https://api.modrinth.com/v2/version_files/update"
MODRINTH_SEARCH_TIMEOUT_SECONDS = 15
MODRINTH_VERSION_TIMEOUT_SECONDS = 15
MODRINTH_PROJECT_BATCH_TIMEOUT_SECONDS = 12
MODRINTH_PROJECT_DETAIL_TIMEOUT_SECONDS = 12
MODRINTH_VERSION_DETAIL_TIMEOUT_SECONDS = 12
MODRINTH_VERSION_FILES_TIMEOUT_SECONDS = 20
MIN_ACCEPTABLE_LOCAL_MOD_SEARCH_SCORE = 70
SUPPORTED_SORT_OPTIONS = {"relevance", "downloads", "newest", "updated", "follows"}
LOCAL_HASH_MAX_WORKERS = 4
MODRINTH_BATCH_HASH_LOOKUP_SIZE = 64
MODRINTH_BATCH_PROJECT_LOOKUP_SIZE = 64
MODRINTH_BATCH_RETRY_ATTEMPTS = 2
MODRINTH_REQUEST_THROTTLE_SECONDS = 0.03
MODRINTH_RETRY_BACKOFF_BASE_SECONDS = 0.25
MODRINTH_RETRY_BACKOFF_MAX_SECONDS = 1.5
MODRINTH_SINGLE_REQUEST_RETRY_ATTEMPTS = 2

__all__ = [
    "LOCAL_HASH_MAX_WORKERS",
    "MIN_ACCEPTABLE_LOCAL_MOD_SEARCH_SCORE",
    "MODRINTH_BATCH_HASH_LOOKUP_SIZE",
    "MODRINTH_BATCH_PROJECT_LOOKUP_SIZE",
    "MODRINTH_BATCH_RETRY_ATTEMPTS",
    "MODRINTH_PROJECT_BATCH_TIMEOUT_SECONDS",
    "MODRINTH_PROJECT_BATCH_URL",
    "MODRINTH_PROJECT_DETAIL_TIMEOUT_SECONDS",
    "MODRINTH_PROJECT_URL",
    "MODRINTH_REQUEST_THROTTLE_SECONDS",
    "MODRINTH_RETRY_BACKOFF_BASE_SECONDS",
    "MODRINTH_RETRY_BACKOFF_MAX_SECONDS",
    "MODRINTH_SEARCH_TIMEOUT_SECONDS",
    "MODRINTH_SEARCH_URL",
    "MODRINTH_SINGLE_REQUEST_RETRY_ATTEMPTS",
    "MODRINTH_VERSION_DETAIL_TIMEOUT_SECONDS",
    "MODRINTH_VERSION_DETAIL_URL_TEMPLATE",
    "MODRINTH_VERSION_FILES_TIMEOUT_SECONDS",
    "MODRINTH_VERSION_FILES_UPDATE_URL",
    "MODRINTH_VERSION_FILES_URL",
    "MODRINTH_VERSION_TIMEOUT_SECONDS",
    "MODRINTH_VERSION_URL_TEMPLATE",
    "SUPPORTED_SORT_OPTIONS",
    "logger",
]
