"""
src/utils/__init__.py
工具模組套件
提供 Minecraft 伺服器管理器應用程式的各種工具函數和輔助類別
"""

from __future__ import annotations

from .. import lazy_exports

_EXPORTS: dict[str, tuple[str, str]] = {
    "SUPPORTED_MODRINTH_UPDATE_LOADERS": (".mod_utils.modrinth_query_utils", "SUPPORTED_MODRINTH_UPDATE_LOADERS"),
    "apply_loader_specific_dependency_override": (
        ".mod_utils.modrinth_query_utils",
        "apply_loader_specific_dependency_override",
    ),
    "build_local_mod_lookup_candidates": (".mod_utils.modrinth_query_utils", "build_local_mod_lookup_candidates"),
    "canonical_lookup_key": (".mod_utils.modrinth_query_utils", "canonical_lookup_key"),
    "clean_api_identifier": (".mod_utils.modrinth_query_utils", "clean_api_identifier"),
    "get_modrinth_loader_filters": (".mod_utils.modrinth_query_utils", "get_modrinth_loader_filters"),
    "is_supported_modrinth_update_loader": (".mod_utils.modrinth_query_utils", "is_supported_modrinth_update_loader"),
    "normalize_identifier": (".mod_utils.modrinth_query_utils", "normalize_identifier"),
    "normalize_local_loader": (".mod_utils.modrinth_query_utils", "normalize_local_loader"),
    "normalize_mod_search_query": (".mod_utils.modrinth_query_utils", "normalize_mod_search_query"),
    "parse_modrinth_version": (".mod_utils.modrinth_query_utils", "parse_modrinth_version"),
    "parse_modrinth_version_lookup_response": (
        ".mod_utils.modrinth_query_utils",
        "parse_modrinth_version_lookup_response",
    ),
    "atomic_write_bytes": (".core_utils.atomic_writer", "atomic_write_bytes"),
    "atomic_write_json": (".core_utils.atomic_writer", "atomic_write_json"),
    "atomic_write_text": (".core_utils.atomic_writer", "atomic_write_text"),
    "best_effort_fsync": (".core_utils.atomic_writer", "best_effort_fsync"),
    "ExceptionUtils": (".core_utils.exception_utils", "ExceptionUtils"),
    "HashUtils": (".core_utils.hash_utils", "HashUtils"),
    "get_logger": (".core_utils.logger", "get_logger"),
    "PathUtils": (".core_utils.path_utils", "PathUtils"),
    "JavaDownloader": (".java_support.java_downloader", "JavaDownloader"),
    "JavaUtils": (".java_support.java_utils", "JavaUtils"),
    "DEPENDENCY_PLAN_PERSISTENCE_SCHEMA_VERSION": (
        ".mod_utils.dependency_plan_serializer",
        "DEPENDENCY_PLAN_PERSISTENCE_SCHEMA_VERSION",
    ),
    "OnlineDependencyInstallItem": (".mod_utils.dependency_plan_serializer", "OnlineDependencyInstallItem"),
    "OnlineDependencyInstallPlan": (".mod_utils.dependency_plan_serializer", "OnlineDependencyInstallPlan"),
    "serialize_online_dependency_install_plan": (
        ".mod_utils.dependency_plan_serializer",
        "serialize_online_dependency_install_plan",
    ),
    "validate_online_dependency_install_plan_payload": (
        ".mod_utils.dependency_plan_serializer",
        "validate_online_dependency_install_plan_payload",
    ),
    "migrate_online_dependency_install_plan_payload": (
        ".mod_utils.dependency_plan_serializer",
        "migrate_online_dependency_install_plan_payload",
    ),
    "deserialize_online_dependency_install_plan": (
        ".mod_utils.dependency_plan_serializer",
        "deserialize_online_dependency_install_plan",
    ),
    "OFFICIAL_DOWNLOAD_HOSTS": (".mod_utils.download_source_policy", "OFFICIAL_DOWNLOAD_HOSTS"),
    "build_non_official_source_warning": (".mod_utils.download_source_policy", "build_non_official_source_warning"),
    "build_non_official_source_warning_message": (
        ".mod_utils.download_source_policy",
        "build_non_official_source_warning_message",
    ),
    "extract_download_host": (".mod_utils.download_source_policy", "extract_download_host"),
    "get_non_official_download_host": (".mod_utils.download_source_policy", "get_non_official_download_host"),
    "get_official_download_hosts": (".mod_utils.download_source_policy", "get_official_download_hosts"),
    "normalize_download_provider": (".mod_utils.download_source_policy", "normalize_download_provider"),
    "collect_installed_mod_identifiers": (".mod_utils.local_mod_metadata_utils", "collect_installed_mod_identifiers"),
    "collect_installed_mod_versions": (".mod_utils.local_mod_metadata_utils", "collect_installed_mod_versions"),
    "dependency_candidate_filenames": (".mod_utils.local_mod_metadata_utils", "dependency_candidate_filenames"),
    "dependency_maybe_installed_by_filename": (
        ".mod_utils.local_mod_metadata_utils",
        "dependency_maybe_installed_by_filename",
    ),
    "normalize_filename_stem": (".mod_utils.local_mod_metadata_utils", "normalize_filename_stem"),
    "normalize_lax_filename": (".mod_utils.local_mod_metadata_utils", "normalize_lax_filename"),
    "expand_required_dependency_install_plan": (
        ".mod_utils.mod_dependency_planner",
        "expand_required_dependency_install_plan",
    ),
    "resolve_dependency_reference": (".mod_utils.mod_dependency_planner", "resolve_dependency_reference"),
    "ModIndexManager": (".mod_utils.mod_index_manager", "ModIndexManager"),
    "LocalProviderEnsureResult": (".mod_utils.mod_provider_metadata", "LocalProviderEnsureResult"),
    "PROVIDER_LIFECYCLE_FRESH": (".mod_utils.mod_provider_metadata", "PROVIDER_LIFECYCLE_FRESH"),
    "PROVIDER_LIFECYCLE_INVALIDATED": (".mod_utils.mod_provider_metadata", "PROVIDER_LIFECYCLE_INVALIDATED"),
    "PROVIDER_LIFECYCLE_MISSING": (".mod_utils.mod_provider_metadata", "PROVIDER_LIFECYCLE_MISSING"),
    "PROVIDER_LIFECYCLE_RETRYING": (".mod_utils.mod_provider_metadata", "PROVIDER_LIFECYCLE_RETRYING"),
    "PROVIDER_LIFECYCLE_STALE": (".mod_utils.mod_provider_metadata", "PROVIDER_LIFECYCLE_STALE"),
    "PROVIDER_METADATA_TTL_SECONDS": (".mod_utils.mod_provider_metadata", "PROVIDER_METADATA_TTL_SECONDS"),
    "PROVIDER_REVALIDATION_BATCH_MAX_PER_RUN": (
        ".mod_utils.mod_provider_metadata",
        "PROVIDER_REVALIDATION_BATCH_MAX_PER_RUN",
    ),
    "ProviderMetadataRecord": (".mod_utils.mod_provider_metadata", "ProviderMetadataRecord"),
    "apply_provider_metadata": (".mod_utils.mod_provider_metadata", "apply_provider_metadata"),
    "cache_provider_metadata_record": (".mod_utils.mod_provider_metadata", "cache_provider_metadata_record"),
    "derive_provider_lifecycle_state": (".mod_utils.mod_provider_metadata", "derive_provider_lifecycle_state"),
    "ensure_local_mod_provider_record": (".mod_utils.mod_provider_metadata", "ensure_local_mod_provider_record"),
    "fetch_modrinth_project_detail": (".mod_utils.mod_provider_metadata", "fetch_modrinth_project_detail"),
    "is_cached_provider_metadata_fresh": (".mod_utils.mod_provider_metadata", "is_cached_provider_metadata_fresh"),
    "is_provider_revalidation_retry_due": (".mod_utils.mod_provider_metadata", "is_provider_revalidation_retry_due"),
    "register_provider_revalidation_success": (
        ".mod_utils.mod_provider_metadata",
        "register_provider_revalidation_success",
    ),
    "resolve_modrinth_provider_record": (".mod_utils.mod_provider_metadata", "resolve_modrinth_provider_record"),
    "should_attempt_provider_revalidation": (
        ".mod_utils.mod_provider_metadata",
        "should_attempt_provider_revalidation",
    ),
    "resolve_revalidation_batch_limits": (
        ".mod_utils.mod_revalidation_batch_utils",
        "resolve_revalidation_batch_limits",
    ),
    "recompute_adaptive_revalidation_batch_limit": (
        ".mod_utils.mod_revalidation_batch_utils",
        "recompute_adaptive_revalidation_batch_limit",
    ),
    "LOCAL_UPDATE_ERROR_METADATA_UNRESOLVED": (".mod_utils.mod_semantics", "LOCAL_UPDATE_ERROR_METADATA_UNRESOLVED"),
    "LOCAL_UPDATE_ERROR_STALE_REVALIDATION_FAILED": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_ERROR_STALE_REVALIDATION_FAILED",
    ),
    "LOCAL_UPDATE_ERROR_STALE_REVALIDATION_INVALIDATED": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_ERROR_STALE_REVALIDATION_INVALIDATED",
    ),
    "LOCAL_UPDATE_GROUP_DETAIL_RETRYABLE": (".mod_utils.mod_semantics", "LOCAL_UPDATE_GROUP_DETAIL_RETRYABLE"),
    "LOCAL_UPDATE_METADATA_NOTE_STALE_REVALIDATION_FAILED": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_METADATA_NOTE_STALE_REVALIDATION_FAILED",
    ),
    "LOCAL_UPDATE_NOTE_CURRENT_VERSION_UNVERIFIED": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_NOTE_CURRENT_VERSION_UNVERIFIED",
    ),
    "LOCAL_UPDATE_NOTE_IDENTIFIED_NO_UPDATE": (".mod_utils.mod_semantics", "LOCAL_UPDATE_NOTE_IDENTIFIED_NO_UPDATE"),
    "LOCAL_UPDATE_NOTE_METADATA_UNRESOLVED": (".mod_utils.mod_semantics", "LOCAL_UPDATE_NOTE_METADATA_UNRESOLVED"),
    "LOCAL_UPDATE_NOTE_PROJECT_FALLBACK_ADVISORY": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_NOTE_PROJECT_FALLBACK_ADVISORY",
    ),
    "LOCAL_UPDATE_NOTE_STALE_BACKOFF_INVALIDATED": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_NOTE_STALE_BACKOFF_INVALIDATED",
    ),
    "LOCAL_UPDATE_NOTE_STALE_BACKOFF_RETRYING": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_NOTE_STALE_BACKOFF_RETRYING",
    ),
    "LOCAL_UPDATE_NOTE_STALE_RETRY_AUTO": (".mod_utils.mod_semantics", "LOCAL_UPDATE_NOTE_STALE_RETRY_AUTO"),
    "LOCAL_UPDATE_PROMPT_ADVISORY_LINE_TEMPLATE": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_PROMPT_ADVISORY_LINE_TEMPLATE",
    ),
    "LOCAL_UPDATE_PROMPT_BLOCKED_LINE_TEMPLATE": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_PROMPT_BLOCKED_LINE_TEMPLATE",
    ),
    "LOCAL_UPDATE_PROMPT_RETRYABLE_LINE_TEMPLATE": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_PROMPT_RETRYABLE_LINE_TEMPLATE",
    ),
    "LOCAL_UPDATE_PROMPT_UNKNOWN_LINE_TEMPLATE": (
        ".mod_utils.mod_semantics",
        "LOCAL_UPDATE_PROMPT_UNKNOWN_LINE_TEMPLATE",
    ),
    "LOCAL_UPDATE_REVIEW_PRECHECK_NOTE": (".mod_utils.mod_semantics", "LOCAL_UPDATE_REVIEW_PRECHECK_NOTE"),
    "LOCAL_UPDATE_SKIPPED_BLOCKED_TEMPLATE": (".mod_utils.mod_semantics", "LOCAL_UPDATE_SKIPPED_BLOCKED_TEMPLATE"),
    "LOCAL_UPDATE_SKIPPED_RETRYABLE_TEMPLATE": (".mod_utils.mod_semantics", "LOCAL_UPDATE_SKIPPED_RETRYABLE_TEMPLATE"),
    "LOCAL_UPDATE_SKIPPED_UNKNOWN_TEMPLATE": (".mod_utils.mod_semantics", "LOCAL_UPDATE_SKIPPED_UNKNOWN_TEMPLATE"),
    "METADATA_SOURCE_CACHED_PROVIDER": (".mod_utils.mod_semantics", "METADATA_SOURCE_CACHED_PROVIDER"),
    "METADATA_SOURCE_HASH": (".mod_utils.mod_semantics", "METADATA_SOURCE_HASH"),
    "METADATA_SOURCE_LABELS": (".mod_utils.mod_semantics", "METADATA_SOURCE_LABELS"),
    "METADATA_SOURCE_LOOKUP": (".mod_utils.mod_semantics", "METADATA_SOURCE_LOOKUP"),
    "METADATA_SOURCE_SHORT_LABELS": (".mod_utils.mod_semantics", "METADATA_SOURCE_SHORT_LABELS"),
    "METADATA_SOURCE_STALE_PROVIDER": (".mod_utils.mod_semantics", "METADATA_SOURCE_STALE_PROVIDER"),
    "METADATA_SOURCE_UNRESOLVED": (".mod_utils.mod_semantics", "METADATA_SOURCE_UNRESOLVED"),
    "ONLINE_INSTALL_NO_ACTIONABLE_MESSAGE": (".mod_utils.mod_semantics", "ONLINE_INSTALL_NO_ACTIONABLE_MESSAGE"),
    "ONLINE_INSTALL_PROMPT_ADVISORY_LINE_TEMPLATE": (
        ".mod_utils.mod_semantics",
        "ONLINE_INSTALL_PROMPT_ADVISORY_LINE_TEMPLATE",
    ),
    "ONLINE_INSTALL_PROMPT_BLOCKED_LINE_TEMPLATE": (
        ".mod_utils.mod_semantics",
        "ONLINE_INSTALL_PROMPT_BLOCKED_LINE_TEMPLATE",
    ),
    "ONLINE_REVIEW_PRECHECK_NOTE": (".mod_utils.mod_semantics", "ONLINE_REVIEW_PRECHECK_NOTE"),
    "RECOMMENDATION_CONFIDENCE_ADVISORY": (".mod_utils.mod_semantics", "RECOMMENDATION_CONFIDENCE_ADVISORY"),
    "RECOMMENDATION_CONFIDENCE_BLOCKED": (".mod_utils.mod_semantics", "RECOMMENDATION_CONFIDENCE_BLOCKED"),
    "RECOMMENDATION_CONFIDENCE_HIGH": (".mod_utils.mod_semantics", "RECOMMENDATION_CONFIDENCE_HIGH"),
    "RECOMMENDATION_CONFIDENCE_LABELS": (".mod_utils.mod_semantics", "RECOMMENDATION_CONFIDENCE_LABELS"),
    "RECOMMENDATION_CONFIDENCE_RETRYABLE": (".mod_utils.mod_semantics", "RECOMMENDATION_CONFIDENCE_RETRYABLE"),
    "RECOMMENDATION_SOURCE_HASH_METADATA": (".mod_utils.mod_semantics", "RECOMMENDATION_SOURCE_HASH_METADATA"),
    "RECOMMENDATION_SOURCE_LABELS": (".mod_utils.mod_semantics", "RECOMMENDATION_SOURCE_LABELS"),
    "RECOMMENDATION_SOURCE_METADATA_UNRESOLVED": (
        ".mod_utils.mod_semantics",
        "RECOMMENDATION_SOURCE_METADATA_UNRESOLVED",
    ),
    "RECOMMENDATION_SOURCE_PROJECT_FALLBACK": (".mod_utils.mod_semantics", "RECOMMENDATION_SOURCE_PROJECT_FALLBACK"),
    "RECOMMENDATION_SOURCE_SHORT_LABELS": (".mod_utils.mod_semantics", "RECOMMENDATION_SOURCE_SHORT_LABELS"),
    "RECOMMENDATION_SOURCE_STALE_METADATA": (".mod_utils.mod_semantics", "RECOMMENDATION_SOURCE_STALE_METADATA"),
    "MODRINTH_PREFERRED_HASH_ALGORITHM": (".mod_utils.mod_version_filtering", "MODRINTH_PREFERRED_HASH_ALGORITHM"),
    "extract_primary_file_hash": (".mod_utils.mod_version_filtering", "extract_primary_file_hash"),
    "is_allowed_version_type": (".mod_utils.mod_version_filtering", "is_allowed_version_type"),
    "normalize_hash_algorithm": (".mod_utils.mod_version_filtering", "normalize_hash_algorithm"),
    "select_best_mod_version": (".mod_utils.mod_version_filtering", "select_best_mod_version"),
    "version_type_priority": (".mod_utils.mod_version_filtering", "version_type_priority"),
    "HTTPUtils": (".network_utils.http_utils", "HTTPUtils"),
    "APP_VERSION": (".runtime_utils.app_info", "APP_VERSION"),
    "APP_NAME": (".runtime_utils.app_info", "APP_NAME"),
    "APP_DESCRIPTION": (".runtime_utils.app_info", "APP_DESCRIPTION"),
    "GITHUB_OWNER": (".runtime_utils.app_info", "GITHUB_OWNER"),
    "GITHUB_REPO": (".runtime_utils.app_info", "GITHUB_REPO"),
    "APP_ID": (".runtime_utils.app_info", "APP_ID"),
    "BackgroundTaskManager": (".runtime_utils.background_task", "BackgroundTaskManager"),
    "run_in_background": (".runtime_utils.background_task", "run_in_background"),
    "CancellationToken": (".runtime_utils.background_task", "CancellationToken"),
    "get_shared_manager": (".runtime_utils.background_task", "get_shared_manager"),
    "RuntimePaths": (".runtime_utils.runtime_paths", "RuntimePaths"),
    "get_settings_manager": (".runtime_utils.settings_manager", "get_settings_manager"),
    "SubprocessUtils": (".runtime_utils.subprocess_utils", "SubprocessUtils"),
    "CREATE_NO_WINDOW": (".runtime_utils.subprocess_utils", "CREATE_NO_WINDOW"),
    "DEVNULL": (".runtime_utils.subprocess_utils", "DEVNULL"),
    "query_winget": (".runtime_utils.subprocess_utils", "query_winget"),
    "is_admin": (".runtime_utils.system_utils", "is_admin"),
    "SystemUtils": (".runtime_utils.system_utils", "SystemUtils"),
    "DEFAULT_WORKER_COUNT": (".runtime_utils.background_task", "DEFAULT_WORKER_COUNT"),
    "get_shared_worker_pool": (".runtime_utils.background_task", "get_shared_worker_pool"),
    "resolve_worker_count": (".runtime_utils.background_task", "resolve_worker_count"),
    "SettingsManager": (".runtime_utils.settings_manager", "SettingsManager"),
    "QProcessResult": (".runtime_utils.subprocess_utils", "QProcessResult"),
    "Singleton": (".runtime_utils.system_utils", "Singleton"),
    "ServerDetectionUtils": (".server_utils.server_detection_utils", "ServerDetectionUtils"),
    "ServerDetectionVersionUtils": (".server_utils.server_detection_utils", "ServerDetectionVersionUtils"),
    "MemoryUtils": (".server_utils.server_memory_utils", "MemoryUtils"),
    "ServerPropertiesHelper": (".server_utils.server_properties_utils", "ServerPropertiesHelper"),
    "ServerPropertiesValidator": (".server_utils.server_properties_utils", "ServerPropertiesValidator"),
    "JvmOptionPolicy": (".server_utils.server_runtime_utils", "JvmOptionPolicy"),
    "ServerCommands": (".server_utils.server_runtime_utils", "ServerCommands"),
    "ServerOperations": (".server_utils.server_runtime_utils", "ServerOperations"),
    "FontManager": (".ui_support.font_manager", "FontManager"),
    "QtCore": (".ui_support.qt_runtime", "QtCore"),
    "QtGui": (".ui_support.qt_runtime", "QtGui"),
    "QtWidgets": (".ui_support.qt_runtime", "QtWidgets"),
    "ValueState": (".ui_support.qt_runtime", "ValueState"),
    "cancel_timer": (".ui_support.qt_runtime", "cancel_timer"),
    "ensure_application": (".ui_support.qt_runtime", "ensure_application"),
    "install_open_url_click": (".ui_support.qt_runtime", "install_open_url_click"),
    "invoke_later": (".ui_support.qt_runtime", "invoke_later"),
    "is_qobject_alive": (".ui_support.qt_runtime", "is_qobject_alive"),
    "run_on_ui_thread": (".ui_support.qt_runtime", "run_on_ui_thread"),
    "TaskUtils": (".ui_support.task_utils", "TaskUtils"),
    "initialize_ui_theme": (".ui_support.ui_config", "initialize_ui_theme"),
    "resolve_color": (".ui_support.ui_config", "resolve_color"),
    "Colors": (".ui_support.ui_tokens", "Colors"),
    "FontSize": (".ui_support.ui_tokens", "FontSize"),
    "Sizes": (".ui_support.ui_tokens", "Sizes"),
    "Spacing": (".ui_support.ui_tokens", "Spacing"),
    "SearchFilter": (".ui_support.ui_state", "SearchFilter"),
    "Variable": (".ui_support.ui_state", "Variable"),
    "TextState": (".ui_support.ui_state", "TextState"),
    "BoolState": (".ui_support.ui_state", "BoolState"),
    "FloatState": (".ui_support.ui_state", "FloatState"),
    "UIUtils": (".ui_support.ui_utils", "UIUtils"),
    "ScrollableComboBox": (".ui_support.ui_utils", "ScrollableComboBox"),
    "UpdateChecker": (".update_utils.update_checker", "UpdateChecker"),
    "UpdateParsing": (".update_utils.update_parsing", "UpdateParsing"),
    "parse_version_safe": (".core_utils.version_utils", "parse_version_safe"),
    "bytes_to_mb": (".core_utils.units_utils", "bytes_to_mb"),
    "format_bytes": (".core_utils.units_utils", "format_bytes"),
}

__getattr__, __dir__, __all__ = lazy_exports(globals(), __name__, _EXPORTS)
