"""
src/models/__init__.py
資料模型套件
提供 Minecraft 伺服器管理器的資料模型定義與相關類別
"""

from __future__ import annotations

from src import lazy_exports

_EXPORTS: dict[str, tuple[str, str]] = {
    "AbstractReviewEntry": (".models", "AbstractReviewEntry"),
    "CatalogOutcomeKind": (".models", "CatalogOutcomeKind"),
    "ConflictType": (".models", "ConflictType"),
    "CreationStatus": (".models", "CreationStatus"),
    "DependencyPlanHooks": (".models", "DependencyPlanHooks"),
    "HTTPJSONResponse": (".models", "HTTPJSONResponse"),
    "ImportMode": (".models", "ImportMode"),
    "ImportSourceKind": (".models", "ImportSourceKind"),
    "ImportStatus": (".models", "ImportStatus"),
    "LoaderInstallerArtifact": (".models", "LoaderInstallerArtifact"),
    "LoaderSpec": (".models", "LoaderSpec"),
    "LoaderVersion": (".models", "LoaderVersion"),
    "LocalMetadataEnsureSummary": (".models", "LocalMetadataEnsureSummary"),
    "LocalModInfo": (".models", "LocalModInfo"),
    "LocalModMutationResult": (".models", "LocalModMutationResult"),
    "LocalModUpdateCandidate": (".models", "LocalModUpdateCandidate"),
    "LocalModUpdatePlan": (".models", "LocalModUpdatePlan"),
    "LocalUpdateReviewEntry": (".models", "LocalUpdateReviewEntry"),
    "MODRINTH_HASH_ALGORITHM": (".models", "MODRINTH_HASH_ALGORITHM"),
    "MODRINTH_SEARCH_URL": (".models", "MODRINTH_SEARCH_URL"),
    "MainWindowSettings": (".models", "MainWindowSettings"),
    "ModFileOperationResult": (".models", "ModFileOperationResult"),
    "ModListRow": (".models", "ModListRow"),
    "ModManagementSnapshot": (".models", "ModManagementSnapshot"),
    "ModOperationScope": (".models", "ModOperationScope"),
    "ModPlatform": (".models", "ModPlatform"),
    "ModStatus": (".models", "ModStatus"),
    "ModrinthVersionLookupResult": (".models", "ModrinthVersionLookupResult"),
    "OnlineBrowseRequest": (".models", "OnlineBrowseRequest"),
    "OnlineDependencyInstallItem": (".models", "OnlineDependencyInstallItem"),
    "OnlineDependencyInstallPlan": (".models", "OnlineDependencyInstallPlan"),
    "OnlineModCompatibilityReport": (".models", "OnlineModCompatibilityReport"),
    "OnlineModInfo": (".models", "OnlineModInfo"),
    "OnlineModVersion": (".models", "OnlineModVersion"),
    "OperationKind": (".models", "OperationKind"),
    "OperationResult": (".models", "OperationResult"),
    "PendingInstallReviewEntry": (".models", "PendingInstallReviewEntry"),
    "PendingOnlineInstall": (".models", "PendingOnlineInstall"),
    "ProviderCatalogOutcome": (".models", "ProviderCatalogOutcome"),
    "ProviderIdentityEvidence": (".models", "ProviderIdentityEvidence"),
    "ProviderIdentitySnapshot": (".models", "ProviderIdentitySnapshot"),
    "ProviderLifecycle": (".models", "ProviderLifecycle"),
    "ResolvedDependencyReference": (".models", "ResolvedDependencyReference"),
    "ReviewContextStamp": (".models", "ReviewContextStamp"),
    "ReviewExecutionHandoff": (".models", "ReviewExecutionHandoff"),
    "ReviewInstallStep": (".models", "ReviewInstallStep"),
    "ReviewMode": (".models", "ReviewMode"),
    "ReviewRootView": (".models", "ReviewRootView"),
    "ReviewTaskNode": (".models", "ReviewTaskNode"),
    "ReviewTaskView": (".models", "ReviewTaskView"),
    "ReviewViewSnapshot": (".models", "ReviewViewSnapshot"),
    "SearchFilter": (".models", "SearchFilter"),
    "ServerConfig": (".models", "ServerConfig"),
    "ServerCreationPlan": (".models", "ServerCreationPlan"),
    "ServerCreationResult": (".models", "ServerCreationResult"),
    "ServerCreationWarning": (".models", "ServerCreationWarning"),
    "ServerDetectionScratch": (".models", "ServerDetectionScratch"),
    "ServerImportBatchResult": (".models", "ServerImportBatchResult"),
    "ServerImportInspection": (".models", "ServerImportInspection"),
    "ServerImportResult": (".models", "ServerImportResult"),
    "ServerOperationResult": (".models", "ServerOperationResult"),
    "ServerProjection": (".models", "ServerProjection"),
    "ServerRefreshPayload": (".models", "ServerRefreshPayload"),
    "ServerRenderPlan": (".models", "ServerRenderPlan"),
    "StartupScriptCommand": (".models", "StartupScriptCommand"),
    "WindowPreferences": (".models", "WindowPreferences"),
    "WorkOutcome": (".models", "WorkOutcome"),
}

__getattr__, __dir__, __all__ = lazy_exports(globals(), __name__, _EXPORTS)
