name: "Google OSS 安全性打分"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions: read-all

jobs:
  analysis:
    if: github.ref == 'refs/heads/master'
    name: Scorecard 分析
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    permissions:
      security-events: write
      id-token: write
      contents: read

    steps:
      - name: "檢出儲存庫"
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - name: "執行 Scorecard 分析"
        uses: ossf/scorecard-action@05bb7c663f6ec9bd8484da0a5b5a77d423e3f88c
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: "上傳至 GitHub Security Tab"
        uses: github/codeql-action/upload-sarif@a899987af240c0578ed84ce13c02319a693e168f
        with:
          sarif_file: results.sarif
          category: oss-scorecard

      - name: "上傳 Scorecard 結果檔案"
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: scorecard-${{ github.sha }}
          path: results.sarif
          retention-days: 2